apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: yelb-catalog-info
  description: A sample catalog for the yelb application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - https://github.com/luckxuqin/tap-catalog/blob/main/components/yelb-ui/yelb-ui.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/components/redis-server/redis-server.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/components/yelb-db/yelb-db.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/components/yelb-appserver/yelb-appserver.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/groups/org.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/systems/yelb-system.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/resources/yelb-db-resource.yaml
    - https://github.com/luckxuqin/tap-catalog/blob/main/domains/cloudapps-domain.yaml
